use ed25519_dalek::{Signer, SigningKey, Verifier, VerifyingKey};
use rand_core::{OsRng, RngCore};
use rdl_types::{Block, Transaction};
use sha2::{Digest, Sha256};
use std::fs;
use std::io::{BufRead, BufReader, Write};
use std::net::{TcpListener, TcpStream};
use std::time::{Duration, Instant};
use std::path::Path;
use std::sync::{Arc, Mutex};
use std::collections::{HashMap, HashSet, VecDeque};
use std::thread;
use std::io::Cursor;

const LEDGER_PATH: &str = "data/rdl-ledger.json";
const IDENTITY_PATH: &str = "data/rdl-node-ed25519.key";
const MAX_BLOCK_TXS: usize = 1_000;
const MAX_MEMPOOL_TXS: usize = 10_000;
const AUTH_DOMAIN: &[u8] = b"RDL-AUTH-v1";
const MAX_FRAME_BYTES: usize = 1_048_576;
const SOCKET_TIMEOUT_SECS: u64 = 10;
const MAX_CONNECTIONS: usize = 64;
const MAX_REQUESTS_PER_CONNECTION: usize = 32;
const MAX_CONNECTIONS_PER_IP: usize = 8;
const MIN_REQUEST_INTERVAL_MS: u64 = 25;
const MAX_REQUESTS_PER_WINDOW: usize = 20;
const RATE_WINDOW_SECS: u64 = 1;
const TLS_CERT_PATH: &str = "data/rdl-tls-cert.pem";
const TLS_KEY_PATH: &str = "data/rdl-tls-key.pem";
const MAX_GOSSIP_PEERS: usize = 16;

fn transaction_id(tx:&Transaction)->[u8;32]{Sha256::digest(serde_json::to_vec(tx).expect("transaction serialization")).into()}
fn admit_transaction(mempool:&mut Vec<Transaction>,seen:&mut HashSet<[u8;32]>,tx:Transaction)->Result<[u8;32],String>{if !tx.verify(){return Err("invalid transaction signature".into())}if mempool.len()>=MAX_MEMPOOL_TXS{return Err("mempool full".into())}let id=transaction_id(&tx);if !seen.insert(id){return Err("duplicate transaction".into())}mempool.push(tx);Ok(id)}
fn configured_peers()->Vec<String>{std::env::var("RDL_BOOTSTRAP_PEERS").ok().map(|v|v.split(',').map(str::trim).filter(|p|!p.is_empty()).take(MAX_GOSSIP_PEERS).map(str::to_owned).collect()).unwrap_or_default()}
fn gossip_transaction(tx:&Transaction){let Ok(payload)=serde_json::to_string(tx)else{return};let message=format!("SUBMIT_TX {}",payload);for peer in configured_peers(){let message=message.clone();thread::spawn(move||{let _=request(&peer,&message);});}}
fn hash_block(block: &Block) -> [u8; 32] { Sha256::digest(serde_json::to_vec(block).expect("block serialization")).into() }
fn load_chain() -> Vec<Block> { if !Path::new(LEDGER_PATH).exists(){return Vec::new()} serde_json::from_slice(&fs::read(LEDGER_PATH).expect("ledger read")).expect("ledger decode") }
fn save_chain(chain:&[Block]) { fs::create_dir_all("data").expect("ledger directory"); fs::write(LEDGER_PATH,serde_json::to_vec_pretty(chain).expect("ledger encode")).expect("ledger write"); }
fn load_or_create_identity()->SigningKey { fs::create_dir_all("data").expect("identity directory"); if let Ok(bytes)=fs::read(IDENTITY_PATH){if let Ok(seed)=<[u8;32]>::try_from(bytes.as_slice()){return SigningKey::from_bytes(&seed)}} let key=SigningKey::generate(&mut OsRng); fs::write(IDENTITY_PATH,key.to_bytes()).expect("identity write"); key }
fn validate_block(block:&Block,previous:Option<&Block>)->Result<(),String>{ if block.transactions.len()>MAX_BLOCK_TXS{return Err("block transaction limit exceeded".into())} for tx in &block.transactions{if !tx.verify(){return Err(format!("invalid transaction signature at height {}",block.height))}} match previous{None if block.height==0&&block.parent_hash==[0;32]=>Ok(()),Some(prev) if block.height==prev.height+1&&block.parent_hash==hash_block(prev)=>Ok(()),_=>Err(format!("invalid block linkage at height {}",block.height))} }
fn validate_chain(chain:&[Block])->Result<(),String>{for(i,b)in chain.iter().enumerate(){validate_block(b,i.checked_sub(1).map(|j|&chain[j]))?}Ok(())}
fn replace_chain_if_valid(local:&mut Vec<Block>,candidate:Vec<Block>)->Result<bool,String>{validate_chain(&candidate)?;if candidate.len()>local.len(){*local=candidate;return Ok(true)}Ok(false)}
fn produce_block(chain:&mut Vec<Block>,mempool:&mut Vec<Transaction>)->Result<(),String>{let previous=chain.last();let block=Block{height:previous.map(|b|b.height+1).unwrap_or(0),parent_hash:previous.map(hash_block).unwrap_or([0;32]),state_root:[0;32],transactions:mempool.drain(..).take(MAX_BLOCK_TXS).collect()};validate_block(&block,previous)?;chain.push(block);Ok(())}
fn hex_encode(bytes:&[u8])->String{bytes.iter().map(|b|format!("{b:02x}")).collect()}
fn decode_hex(s:&str)->Result<Vec<u8>,String>{if s.len()%2!=0{return Err("invalid hex".into())}(0..s.len()).step_by(2).map(|i|u8::from_str_radix(&s[i..i+2],16).map_err(|_|"invalid hex".into())).collect()}
fn auth_payload(nonce:&[u8;32])->Vec<u8>{[AUTH_DOMAIN,nonce].concat()}
fn auth_message(key:&SigningKey,nonce:&[u8;32])->String{let public=key.verifying_key().to_bytes();let sig=key.sign(&auth_payload(nonce)).to_bytes();format!("AUTH {} {}",hex_encode(&public),hex_encode(&sig))}
fn verify_auth_key(line:&str,nonce:&[u8;32])->Option<[u8;32]>{let mut p=line.split_whitespace();if p.next()!=Some("AUTH"){return None}let(Some(pk),Some(sig))=(p.next(),p.next())else{return None};let Ok(pk)=decode_hex(pk)else{return None};let Ok(sig)=decode_hex(sig)else{return None};let Ok(pk)=<[u8;32]>::try_from(pk.as_slice())else{return None};let Ok(key)=VerifyingKey::from_bytes(&pk)else{return None};let Ok(sig)=ed25519_dalek::Signature::from_slice(&sig)else{return None};if key.verify(&auth_payload(nonce),&sig).is_ok(){Some(pk)}else{None}}
fn peer_authorized(pk:&[u8;32])->bool{match std::env::var("RDL_AUTHORIZED_PEERS"){Ok(list)=>{let id=hex_encode(pk);list.split(',').map(str::trim).any(|x|x==id)},Err(_)=>true}}
fn identity_rate_allowed(limits:&mut HashMap<[u8;32],VecDeque<Instant>>,pk:[u8;32])->bool{let now=Instant::now();let window=Duration::from_secs(RATE_WINDOW_SECS);let q=limits.entry(pk).or_default();while q.front().is_some_and(|t|now.duration_since(*t)>=window){q.pop_front();}if q.len()>=MAX_REQUESTS_PER_WINDOW{return false}q.push_back(now);true}
fn read_bounded_line(reader:&mut BufReader<TcpStream>)->std::io::Result<String>{let mut line=String::new();let n=reader.read_line(&mut line)?;if n==0{return Err(std::io::Error::new(std::io::ErrorKind::UnexpectedEof,"peer closed connection"))}if line.len()>MAX_FRAME_BYTES{return Err(std::io::Error::new(std::io::ErrorKind::InvalidData,"frame too large"))}Ok(line)}
fn issue_challenge(stream:&mut TcpStream)->std::io::Result<[u8;32]>{let mut nonce=[0u8;32];OsRng.fill_bytes(&mut nonce);stream.write_all(format!("CHALLENGE {}\n",hex_encode(&nonce)).as_bytes())?;Ok(nonce)}
fn read_challenge(reader:&mut BufReader<TcpStream>)->std::io::Result<[u8;32]>{let line=read_bounded_line(reader)?;let mut p=line.split_whitespace();if p.next()!=Some("CHALLENGE"){return Err(std::io::Error::new(std::io::ErrorKind::InvalidData,"missing challenge"))}let hex=p.next().ok_or_else(||std::io::Error::new(std::io::ErrorKind::InvalidData,"missing nonce"))?;let bytes=decode_hex(hex).map_err(std::io::Error::other)?;<[u8;32]>::try_from(bytes.as_slice()).map_err(|_|std::io::Error::new(std::io::ErrorKind::InvalidData,"invalid nonce"))}
fn tls_material_present()->bool{Path::new(TLS_CERT_PATH).exists()&&Path::new(TLS_KEY_PATH).exists()}
fn load_tls_cert_chain()->std::io::Result<Vec<rustls::pki_types::CertificateDer<'static>>>{let data=fs::read(TLS_CERT_PATH)?;let mut reader=Cursor::new(data);rustls_pemfile::certs(&mut reader).collect::<Result<Vec<_>,_>>().map_err(std::io::Error::other)}
fn load_tls_private_key()->std::io::Result<rustls::pki_types::PrivateKeyDer<'static>>{let data=fs::read(TLS_KEY_PATH)?;let mut reader=Cursor::new(data);rustls_pemfile::private_key(&mut reader)?.ok_or_else(||std::io::Error::new(std::io::ErrorKind::InvalidData,"no private key found"))}
fn validate_tls_material()->std::io::Result<()> {if !tls_material_present(){return Ok(())}let certs=load_tls_cert_chain()?;let key=load_tls_private_key()?;rustls::ServerConfig::builder().with_no_client_auth().with_single_cert(certs,key).map_err(std::io::Error::other)?;Ok(())}
fn configure_socket(stream:&TcpStream)->std::io::Result<()> {let timeout=Some(Duration::from_secs(SOCKET_TIMEOUT_SECS));stream.set_read_timeout(timeout)?;stream.set_write_timeout(timeout)?;stream.set_nodelay(true)?;Ok(())}
fn handle_peer(mut stream:TcpStream,chain:&mut Vec<Block>,mempool:&Arc<Mutex<Vec<Transaction>>>,seen_txs:&Arc<Mutex<HashSet<[u8;32]>>>,identity_limits:&Arc<Mutex<HashMap<[u8;32],VecDeque<Instant>>>>)->std::io::Result<()> {configure_socket(&stream)?;let nonce=issue_challenge(&mut stream)?;let mut reader=BufReader::new(stream.try_clone()?);let auth=read_bounded_line(&mut reader)?;let Some(peer_key)=verify_auth_key(auth.trim(),&nonce) else {stream.write_all(b"UNAUTHENTICATED\n")?;return Ok(())};if !peer_authorized(&peer_key){stream.write_all(b"UNAUTHORIZED\n")?;return Ok(())}let mut last_request=Instant::now()-Duration::from_millis(MIN_REQUEST_INTERVAL_MS);for _ in 0..MAX_REQUESTS_PER_CONNECTION {let globally_allowed={let mut limits=identity_limits.lock().map_err(|_|std::io::Error::other("rate limiter poisoned"))?;identity_rate_allowed(&mut limits,peer_key)};if !globally_allowed{stream.write_all(b"IDENTITY_RATE_LIMITED\n")?;return Ok(())}let elapsed=last_request.elapsed();let minimum=Duration::from_millis(MIN_REQUEST_INTERVAL_MS);if elapsed<minimum{stream.write_all(b"RATE_LIMITED\n")?;return Ok(())}last_request=Instant::now();let line=read_bounded_line(&mut reader)?;match line.trim(){"PING"=>stream.write_all(b"PONG\n")?,"GET_HEIGHT"=>stream.write_all(format!("HEIGHT {}\n",chain.last().map(|b|b.height).unwrap_or(0)).as_bytes())?,"GET_TIP_HASH"=>stream.write_all(format!("TIP {}\n",hex_encode(&chain.last().map(hash_block).unwrap_or([0;32]))).as_bytes())?,"GET_CHAIN"=>{stream.write_all(serde_json::to_string(chain).map_err(std::io::Error::other)?.as_bytes())?;stream.write_all(b"\n")?},message if message.starts_with("SUBMIT_TX ")=>{let tx:Transaction=serde_json::from_str(message.trim_start_matches("SUBMIT_TX ")).map_err(std::io::Error::other)?;let result={let mut pool=mempool.lock().map_err(|_|std::io::Error::other("mempool lock poisoned"))?;let mut seen=seen_txs.lock().map_err(|_|std::io::Error::other("seen transaction lock poisoned"))?;admit_transaction(&mut pool,&mut seen,tx)};match result{Ok(id)=>{gossip_transaction(&tx);stream.write_all(format!("TX_ACCEPTED {}\n",hex_encode(&id)).as_bytes())?},Err(reason)=>stream.write_all(format!("TX_REJECTED {}\n",reason).as_bytes())?}},message if message.starts_with("SUBMIT_BLOCK ")=>{let block:Block=serde_json::from_str(message.trim_start_matches("SUBMIT_BLOCK ")).map_err(std::io::Error::other)?;match validate_block(&block,chain.last()){Ok(())=>{chain.push(block);save_chain(chain);stream.write_all(b"ACCEPTED\n")?},Err(_)=>stream.write_all(b"REJECTED\n")?}},_=>stream.write_all(b"ERROR unknown_message\n")?}}stream.write_all(b"CONNECTION_REQUEST_LIMIT\n")?;Ok(())}
fn run_listener(addr:&str)->std::io::Result<()> {validate_tls_material()?;if !tls_material_present(){return Err(std::io::Error::new(std::io::ErrorKind::NotFound,"TLS certificate/key required for listener; refusing plaintext reality-mode listener"))}let listener=TcpListener::bind(addr)?;listener.set_nonblocking(true)?;let chain=Arc::new(Mutex::new(load_chain()));validate_chain(&chain.lock().map_err(|_|std::io::Error::other("chain lock poisoned"))?).map_err(std::io::Error::other)?;let active=Arc::new(std::sync::atomic::AtomicUsize::new(0));let per_ip=Arc::new(Mutex::new(HashMap::<std::net::IpAddr,usize>::new()));let identity_limits=Arc::new(Mutex::new(HashMap::<[u8;32],VecDeque<Instant>>::new()));let mempool=Arc::new(Mutex::new(Vec::<Transaction>::new()));let seen_txs=Arc::new(Mutex::new(HashSet::<[u8;32]>::new()));println!("RDL secure-transport-gated node listening on {}; TLS material validated",addr);loop{match listener.accept(){Ok((stream,peer_addr))=>{if active.load(std::sync::atomic::Ordering::Relaxed)>=MAX_CONNECTIONS{drop(stream);continue}let ip=peer_addr.ip();let allowed={let mut counts=per_ip.lock().map_err(|_|std::io::Error::other("peer map poisoned"))?;let count=counts.entry(ip).or_insert(0);if *count>=MAX_CONNECTIONS_PER_IP{false}else{*count+=1;true}};if !allowed{drop(stream);continue}let chain=Arc::clone(&chain);let active=Arc::clone(&active);let per_ip=Arc::clone(&per_ip);let identity_limits=Arc::clone(&identity_limits);let mempool=Arc::clone(&mempool);let seen_txs=Arc::clone(&seen_txs);active.fetch_add(1,std::sync::atomic::Ordering::Relaxed);thread::spawn(move||{if let Ok(mut guard)=chain.lock(){let _=handle_peer(stream,&mut guard,&mempool,&seen_txs,&identity_limits);}if let Ok(mut counts)=per_ip.lock(){if let Some(count)=counts.get_mut(&ip){*count=count.saturating_sub(1);if *count==0{counts.remove(&ip);}}}active.fetch_sub(1,std::sync::atomic::Ordering::Relaxed);});},Err(e) if e.kind()==std::io::ErrorKind::WouldBlock=>thread::sleep(Duration::from_millis(10)),Err(e)=>return Err(e)}}}
fn request(addr:&str,message:&str)->std::io::Result<String>{if !tls_material_present(){return Err(std::io::Error::new(std::io::ErrorKind::NotFound,"TLS certificate/key required by reality-mode client"))}validate_tls_material()?;let mut stream=TcpStream::connect_timeout(&addr.parse().map_err(|_|std::io::Error::new(std::io::ErrorKind::InvalidInput,"invalid peer address"))?,Duration::from_secs(SOCKET_TIMEOUT_SECS))?;configure_socket(&stream)?;let mut reader=BufReader::new(stream.try_clone()?);let nonce=read_challenge(&mut reader)?;let identity=load_or_create_identity();stream.write_all(format!("{}\n{}\n",auth_message(&identity,&nonce),message).as_bytes())?;let response=read_bounded_line(&mut reader)?;Ok(response.trim().to_string())}
fn sync_from_peer(addr:&str)->Result<(),String>{let payload=request(addr,"GET_CHAIN").map_err(|e|e.to_string())?;let candidate:Vec<Block>=serde_json::from_str(&payload).map_err(|e|e.to_string())?;let mut local=load_chain();validate_chain(&local)?;if replace_chain_if_valid(&mut local,candidate)?{save_chain(&local);println!("SYNCED blocks={}",local.len())}else{println!("SYNC_NOT_NEEDED")}Ok(())}
fn main(){let args:Vec<String>=std::env::args().collect();if args.len()==3&&args[1]=="--listen"{run_listener(&args[2]).expect("listener");return}if args.len()==3&&args[1]=="--sync"{sync_from_peer(&args[2]).expect("peer sync");return}if args.len()==3&&(args[1]=="--ping"||args[1]=="--height"||args[1]=="--tip"){let command=match args[1].as_str(){"--ping"=>"PING","--height"=>"GET_HEIGHT",_=>"GET_TIP_HASH"};println!("{}",request(&args[2],command).expect("peer request"));return}let mut chain=load_chain();validate_chain(&chain).expect("existing ledger validation");if chain.is_empty(){chain.push(Block{height:0,parent_hash:[0;32],state_root:[0;32],transactions:vec![]})}let key=SigningKey::generate(&mut OsRng);let mut tx=Transaction{from:String::new(),to:"rdl_demo_recipient".into(),nonce:0,payload:b"RDL signed transaction".to_vec(),public_key:vec![],signature:vec![]};tx.sign(&key);let mut mempool=vec![tx];produce_block(&mut chain,&mut mempool).expect("block production");validate_chain(&chain).expect("chain validation");save_chain(&chain);println!("RDL Node v0.1.0 — challenge-authenticated development peer foundation");println!("STATUS: challenge-response authentication, optional peer allowlist, bounded frames, socket timeouts, connection concurrency limits, per-IP caps, per-connection request limits, request pacing and shared identity-aware rate limiting, TLS material gating, bounded transaction admission, and bootstrap-peer transaction propagation implemented; encrypted rustls stream integration, block gossip, production consensus and testnet remain pending.");}